import { NextResponse } from "next/server";
import { ObjectId } from "mongodb";

import client from "@/lib/mongodb";
import { runOrderSolve } from "@/lib/solver/server/runOrderSolve";
import { generateOrderId } from "@/lib/orders/generateOrderId";

export async function POST(request: Request) {
  // Machine-to-machine auth: shared API key header, not a user cookie.
  const apiKey = request.headers.get("x-api-key");
  const expected = process.env.ORDER_INTAKE_API_KEY;

  if (!expected || apiKey !== expected) {
    return NextResponse.json(
      { error: "Unauthorised" },
      { status: 401 }
    );
  }

  try {
    const body = (await request.json()) as Record<string, unknown>;

    /*
     * orderId is generated by the system.
     *
     * Do not trust/use an orderId supplied by the external sender.
     */
    const orderId = generateOrderId();

    // Remove incoming orderId so the client cannot override
    // the system-generated value.
    const { orderId: _ignoredOrderId, ...orderData } = body;

    // Build the actual order stored by the system.
    const order = {
      ...orderData,

      // System-generated ID
      orderId,

      // External senders may omit these.
      source: body.source ?? "External",
      status: body.status ?? "Available",
    };

    const dbName = process.env.MONGODB_DB || "fitvisualizer";
    const db = client.db(dbName);
    const collection = db.collection("orders");

    /*
     * Optionally associate the incoming order with an existing customer.
     * If no customerId is supplied, staff can assign it later.
     */
    let customerId: string | null = null;
    let customerName = "Unassigned";

    const rawCustomerId = String(body.customerId ?? "").trim();

    if (rawCustomerId) {
      if (!ObjectId.isValid(rawCustomerId)) {
        return NextResponse.json(
          { error: "Invalid customerId." },
          { status: 400 }
        );
      }

      const cust = await db.collection("users").findOne(
        {
          _id: new ObjectId(rawCustomerId),
        },
        {
          projection: {
            username: 1,
          },
        }
      );

      if (!cust) {
        return NextResponse.json(
          { error: "Customer not found." },
          { status: 404 }
        );
      }

      customerId = rawCustomerId;
      customerName = String(cust.username ?? "Unknown");
    }

    const now = new Date();

    /*
     * This is a newly created order, so insert it rather than
     * looking for an orderId supplied by the client.
     */
    await collection.insertOne({
      ...order,

      customerId,
      customerName,

      progress: "submitted",

      createdAt: now,
      updatedAt: now,
    });

    /*
     * The exact same system-generated orderId is now used
     * throughout the solver/packing lifecycle.
     */
    await runOrderSolve(orderId);

    /*
     * Retrieve the saved order after solving.
     */
    const saved = await collection.findOne(
      { orderId },
      {
        projection: {
          _id: 0,
          ownerUserId: 0,
        },
      }
    );

    return NextResponse.json(saved, {
      status: 201,
    });
  } catch (error) {
    console.error("Order intake failed:", error);

    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Order intake failed",
      },
      { status: 400 }
    );
  }
}